services:
  - type: web
    name: sistema-ejc-backend
    env: node
    plan: free
    rootDirectory: backend
    buildCommand: npm install && npm run migrate:deploy && npm run prisma:seed
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "file:./dev.db"
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false

